homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
tableOfContents:
  - page: getting-started
  - page: app
    children:
      - page: modules
        children:
          - page: modules/core
            children:
              - page: modules/core/billing
                children:
                  - page: modules/core/billing/models/billing-account
                  - page: modules/core/billing/models/billing-account-service
                  - page: modules/core/billing/controllers/billing-accounts
                  - page: modules/core/billing/views/billing-accounts
                  - page: modules/core/billing/components/table-billing-account-services
              - page: modules/core/customers
  - page: extensions
    children:
      - page: controllers
      - page: views
      - page: ui-components
      - page: routing
      - page: permissions
  - page: rest-api
  - page: examples
