homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
tableOfContents:
  - json: '{ "page": "home", "icon": "fas fa-home", "next": "features" }'
  - json: '{ "page": "features", "icon": "fas fa-check", "prev": "home", "next": "download-and-install" }'
  - json: '{ "page": "download-and-install", "icon": "fas fa-download", "prev": "features", "next": "create-first-app" }'
  - json: '{ "page": "create-first-app", "icon": "fas fa-star", "prev": "download-and-install", "next": "app-development" }'
  - page: app-development
    icon: fas fa-code
    children:
      - page: loader
      - page: model
      - page: eloquent
      - page: controller
      - page: view
      - page: component
      - page: ui-components
        children:
          - page: ui-components/form-component
      - page: routing
      - page: permissions
  - page: apps
    icon: fas fa-bolt
    children:
      - page: apps/core
        children:
          - page: apps/core/billing
            children:
              - page: apps/core/billing/models/billing-account
              - page: apps/core/billing/models/billing-account-service
              - page: apps/core/billing/controllers/billing-accounts
              - page: apps/core/billing/views/billing-accounts
              - page: apps/core/billing/components/table-billing-account-services
          - page: apps/core/customers
            children:
              - page: apps/core/customers/models/activity
              - page: apps/core/customers/models/address
              - page: apps/core/customers/models/company
              - page: apps/core/customers/models/company-tag
              - page: apps/core/customers/models/company-activity
              - page: apps/core/customers/models/company-document
              - page: apps/core/customers/models/contact
              - page: apps/core/customers/models/person-tag
              - page: apps/core/customers/models/person
              - page: apps/core/customers/permissions
          - page: apps/core/documents
            children:
              - page: apps/core/documents/models/document
              - page: apps/core/documents/permissions
          - page: apps/core/services
            children:
              - page: apps/core/services/models/service
              - page: apps/core/services/permissions
          - page: apps/core/settings
            children:
              - page: apps/core/settings/models/activity-type
              - page: apps/core/settings/models/country
              - page: apps/core/settings/models/currency
              - page: apps/core/settings/models/label
              - page: apps/core/settings/models/pipeline
              - page: apps/core/settings/models/pipeline-step
              - page: apps/core/settings/models/lead-status
              - page: apps/core/settings/models/deal-status
              - page: apps/core/settings/models/profile
              - page: apps/core/settings/models/permission
              - page: apps/core/settings/models/role-permission
              - page: apps/core/settings/models/setting
              - page: apps/core/settings/models/tag
              - page: apps/core/settings/models/contact-type
              - page: apps/core/settings/models/user
              - page: apps/core/settings/models/user-role
              - page: apps/core/settings/models/user-has-role
              - page: apps/core/settings/permissions
      - page: apps/sales
        children:
          - page: apps/sales/deals
            children:
              - page: apps/sales/deals/models/deal
              - page: apps/sales/deals/models/deal-label
              - page: apps/sales/deals/models/deal-history
              - page: apps/sales/deals/models/deal-service
              - page: apps/sales/deals/models/deal-activity
              - page: apps/sales/deals/settings
          - page: apps/sales/leads
            children:
              - page: apps/sales/leads/models/lead
              - page: apps/sales/leads/models/lead-label
              - page: apps/sales/leads/models/lead-history
              - page: apps/sales/leads/models/lead-service
              - page: apps/sales/leads/models/lead-activity
  # - page: rest-api
  # - page: examples
