homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
tableOfContents:
  - page: getting-started
  - page: app
    children:
      - page: modules
        children:
          - page: getting-started
          - page: modules/core
            children:
              - page: modules/core/billing
                children:
                  - page: modules/core/billing/models/billing-account
                  - page: modules/core/billing/models/billing-account-service
                  - page: modules/core/billing/controllers/billing-accounts
                  - page: modules/core/billing/views/billing-accounts
                  - page: modules/core/billing/components/table-billing-account-services
              - page: modules/core/customers
                children:
                  - page: modules/core/customers/models/activity
                  - page: modules/core/customers/models/address
                  - page: modules/core/customers/models/company-tag
                  - page: modules/core/customers/models/company
                  - page: modules/core/customers/models/contact
                  - page: modules/core/customers/models/person-tag
                  - page: modules/core/customers/models/person
                  - page: modules/core/customers/permissions
              - page: modules/core/documents
                children:
                  - page: modules/core/documents/models/document
                  - page: modules/core/documents/permissions
              - page: modules/core/services
                children:
                  - page: modules/core/services/models/service
                  - page: modules/core/services/permissions
              - page: modules/core/settings
                children:
                  - page: modules/core/settings/models/activity-type
                  - page: modules/core/settings/models/country
                  - page: modules/core/settings/models/currency
                  - page: modules/core/settings/models/label
                  - page: modules/core/settings/models/permission
                  - page: modules/core/settings/models/pipeline-step
                  - page: modules/core/settings/models/pipeline
                  - page: modules/core/settings/models/profile
                  - page: modules/core/settings/models/role-permission
                  - page: modules/core/settings/models/setting
                  - page: modules/core/settings/models/tag
                  - page: modules/core/settings/models/user-has-role
                  - page: modules/core/settings/models/user-role
                  - page: modules/core/settings/models/user
                  - page: modules/core/settings/permissions
          - page: modules/sales
            children:
              - page: modules/sales/deals
                children:
                  - page: modules/sales/deals/models/deal
                  - page: modules/sales/deals/models/deal-label
                  - page: modules/sales/deals/models/deal-history
                  - page: modules/sales/deals/models/deal-service
                  - page: modules/sales/deals/settings
              - page: modules/sales/leads
                children:
                  - page: modules/sales/leads/models/lead
                  - page: modules/sales/leads/models/lead-label
                  - page: modules/sales/leads/models/lead-history
                  - page: modules/sales/leads/models/lead-service
  - page: extensions
    children:
      - page: controllers
      - page: views
      - page: ui-components
      - page: routing
      - page: permissions
  - page: rest-api
  - page: examples
