homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
router:
tableOfContents:
  - json: '{ "page": "home", "icon": "fas fa-home", "next": "features" }'
  - json: '{ "page": "features", "icon": "fas fa-check", "prev": "home", "next": "download-and-install" }'
  - page: download-and-install
    icon: fas fa-download
    prev: features
    next: create-first-app
    children:
      - page: nginx
      - page: cli-agent
  - page: create-first-app
    icon: fas fa-star
    prev: download-and-install
    next: tutorial/add-first-model
    children:
      - page: tutorial/add-first-model
        prev: create-first-app
        next: tutorial/add-1-n-relation
      - page: tutorial/add-1-n-relation
        prev: tutorial/add-first-model
        next: tutorial/customize-tables-and-forms
      - page: tutorial/customize-tables-and-forms
        prev: tutorial/add-1-n-relation
        next: tutorial/custom-ui-components
      - page: tutorial/custom-ui-components
        prev: tutorial/customize-tables-and-forms
        next: tutorial/writing-tests
      - page: tutorial/writing-tests
        prev: tutorial/custom-ui-components
        next: tutorial/more-reading
      - page: tutorial/more-reading
        prev: tutorial/writing-tests
        next: advanced-development
  - page: advanced-development
    icon: fas fa-medal
    children:
      - page: advanced-development/core-architecture
      - page: advanced-development/description-api
        children:
          - page: advanced-development/description-api/table
          - page: advanced-development/description-api/form
      - page: advanced-development/core-classes
        icon: fas fa-code
        children:
          - page: advanced-development/core-classes/loader
          - page: advanced-development/core-classes/model
          - page: advanced-development/core-classes/eloquent
          - page: advanced-development/core-classes/controller
          - page: advanced-development/core-classes/router
          - page: advanced-development/core-classes/permissions
      - page: advanced-development/customizing-ui
        children:
          - page: advanced-development/customizing-ui/view
          - page: advanced-development/customizing-ui/component
          - page: advanced-development/customizing-ui/forms
          - page: advanced-development/customizing-ui/special-input-types
          - page: advanced-development/customizing-ui/skin
  - page: contribute
    icon: fas fa-terminal
  - page: apps
    icon: fas fa-bolt
    children:
      - page: apps/community
        children:
          - page: apps/community/billing
            children:
              - page: apps/community/billing/models/billing-account
              - page: apps/community/billing/models/billing-account-service
              - page: apps/community/billing/controllers/billing-accounts
              - page: apps/community/billing/views/billing-accounts
              - page: apps/community/billing/components/table-billing-account-services
          - page: apps/community/customers
            children:
              - page: apps/community/customers/models/activity
              - page: apps/community/customers/models/address
              - page: apps/community/customers/models/company
              - page: apps/community/customers/models/company-tag
              - page: apps/community/customers/models/company-activity
              - page: apps/community/customers/models/company-document
              - page: apps/community/customers/models/contact
              - page: apps/community/customers/models/person-tag
              - page: apps/community/customers/models/person
              - page: apps/community/customers/permissions
          - page: apps/community/documents
            children:
              - page: apps/community/documents/models/document
              - page: apps/community/documents/permissions
          - page: apps/community/services
            children:
              - page: apps/community/services/models/service
              - page: apps/community/services/permissions
          - page: apps/community/settings
            children:
              - page: apps/community/settings/models/activity-type
              - page: apps/community/settings/models/country
              - page: apps/community/settings/models/currency
              - page: apps/community/settings/models/label
              - page: apps/community/settings/models/pipeline
              - page: apps/community/settings/models/pipeline-step
              - page: apps/community/settings/models/lead-status
              - page: apps/community/settings/models/deal-status
              - page: apps/community/settings/models/profile
              - page: apps/community/settings/models/permission
              - page: apps/community/settings/models/role-permission
              - page: apps/community/settings/models/setting
              - page: apps/community/settings/models/tag
              - page: apps/community/settings/models/contact-type
              - page: apps/community/settings/models/user
              - page: apps/community/settings/models/user-role
              - page: apps/community/settings/models/user-has-role
              - page: apps/community/settings/permissions
          - page: apps/community/deals
            children:
              - page: apps/community/deals/models/deal
              - page: apps/community/deals/models/deal-label
              - page: apps/community/deals/models/deal-history
              - page: apps/community/deals/models/deal-service
              - page: apps/community/deals/models/deal-activity
              - page: apps/community/deals/settings
          - page: apps/community/leads
            children:
              - page: apps/community/leads/models/lead
              - page: apps/community/leads/models/lead-label
              - page: apps/community/leads/models/lead-history
              - page: apps/community/leads/models/lead-service
              - page: apps/community/leads/models/lead-activity
          - page: apps/community/calendar-sync
      - page: apps/enterprise
      - page: apps/external
  - page: partnership
    icon: fas fa-handshake-angle
  - page: licenses
    icon: fas fa-stamp
  - page: improve
    icon: fas fa-heart
  - page: download
    icon: fas fa-file
  # - page: examples
